### ISSUE TITLE
Inclure le glossaire dans tous les contenus

### ISSUE THREAD

**Issue by Guts** [geotribu/website#473]
Actuellement, pour inclure le [glossaire](https://github.com/geotribu/website/blob/master/content/toc_nav_ignored/snippets/glossaire.md?plain=1), il faut utiliser un include en fin de fichier :

```markdown
<!-- Intègre le glossaire centralisé -->
--8<-- "content/toc_nav_ignored/snippets/glossaire.md"
```

Avec l'option `auto_append` de l'extension Snippets des extensions Python Markdown (cf [la doc](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#auto-append-snippets)), on pourrait éviter cette ligne manuelle en indiquant dans le `mkdocs.yml` :

```yaml
[...]
  - pymdownx.snippets:
      auto_append: [
        content/toc_nav_ignored/snippets/glossaire.md,
      ]
      base_path: "."
      check_paths: true
[...]
```

Avantage : le glossaire est inclus par défaut, sans action supplémentaire et s'applique partout.  
Inconvénient : il s'applique dans tous les contenus et il ne sera pas possible de l'enlever au cas par cas.

Pour avis.
